services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    env_file:
#      - .env
    environment:
      - TZ=America/Caracas
    container_name: app
    ports:
      - "8000:8000"
    command: python3 run.py
    networks:
      - tutorial_fastapi_api
    restart: always
#    depends_on:
#      - db
#    volumes:
#      - ./app:/app/app



networks:
  tutorial_fastapi_api:
    driver: bridge
